# Default configurations
defaults:
  - dataset: MSL            # Default dataset setting
  - model: Transformer_RBF # Default model setting - Select Transformer_RBF model for the experiment with RESTAD model. 
  - _self_
  
  
# Initialization method for RBF layer
initialization: "random"

# Available choices for initialization
# initialization_choices: 
    # 1) 2steps  # Two-step initialization: 1) Pretrain the base model, 2) Use the pretrained model to derive initial values for RBF (e.g., using K-means) 
    # 2) random   # Random initialization for the RBF layer


# Phase of the experiment
mode: "main_train"

# Available choices for mode
# mode_choices:
    # 1) pretrain    # Pretraining phase without RBF
    # 2) main_train  # Main training phase with RBF


# Seed for reproducibility
seed: 0

# Execution environment
environment: local

# Device for training
device: "auto"


