type: "LSTM"

base_model_type: "LSTM" # This is the type of the model in phase 1

#model configuration
input_size: ${dataset.x_dim}
hidden_size: 80

#Optimization configuration
batch_size: 64
num_epochs: 100

lr: 1e-2
weight_decay: 0
dropout: 0
clip_grad: 1


# Optimized HyperParameters: 
    # MSL:  hidden = 80
    #       batch_size = 64
    #       num_epochs = 100
    #       lr = 1e-2
    #       w_d: 1e-5
    #       dropout: 0
    #       clip_grad: 1
    
    
    
# Optimized HyperParameters: 
    # PSM:  hidden = 80
    #       batch_size = 64
    #       num_epochs = 100
    #       lr = 1e-3
    #       w_d: 1e-5
    #       dropout: 0
    #       clip_grad: 1



# Optimized HyperParameters:
    # SMD:  hidden = 80
    #       batch_size = 64
    #       num_epochs = 200
    #       lr = 1e-2
    #       w_d: 0
    #       dropout: 0
    #       clip_grad: 1
